#!/bin/bash 

#this is the test version using the INI version of the doc
#TIMESTAMP=$(curl -u usuario52:Ken7ohme https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html 2>&1 | grep 'TXTOTCO99INI' | sed -n 's/.*href="\([^"]*\).*/\1/p' | sed 's/\.//' )

#this is the real version getting the hours and minutes

 while true
 do
 	TIMESTAMP=$(curl -u usuario52:Ken7ohme https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html 2>&1 | grep 'TXTOTCO99hhmm' | sed -n 's/.*href="\([^"]*\).*/\1/p')

    echo 'hitting this url'
    echo https://descargas.10noviembre2019.es/web/datos/$TIMESTAMP


    curl -u usuario552:aiw4Yeiw https://descargas.10noviembre2019.es/web/datos/$TIMESTAMP | gzip -d > ./src/server/latestraw.csv


    npm run provinces-parser
    npm run deploylive
    sleep 300
done
