#!/bin/bash 
# TIMESTAMP=$(curl -u usuario52:Ken7ohme https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html 2>&1 | grep 'TXTOTCO99hhmm' | sed -n 's/.*href="\([^"]*\).*/\1/p')

# curl -u usuario52:Ken7ohme https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html

# while true
# do
curl -u usuario52:Ken7ohme https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html | gzip -d > ./src/assets/latestraw.csv
gulp provinces-parser
gulp
# gulp deploypreview
# sleep 300
# done
