#!/bin/bash 

#this is the test version using the INI version of the doc
#TIMESTAMP=$(curl -u usuario52:Ken7ohme https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html 2>&1 | grep 'TXTOTCO99INI' | sed -n 's/.*href="\([^"]*\).*/\1/p' | sed 's/\.//' )

#this is the real version getting the hours and minutes
TIMESTAMP=$(curl -u usuario52:Ken7ohme https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html 2>&1 | grep 'TXTOTCO99hhmm' | sed -n 's/.*href="\([^"]*\).*/\1/p')

 while true
 do
    current_time=$(date "+%Y.%m.%d-%H.%M.%S")
    echo current_time

    curl -u usuario552:aiw4Yeiw https://descargas.10noviembre2019.es/web/datos/DESCAR99_L1.html > ./src/assets/$current_time

    sleep 300
done
